### ISSUE TITLE
README and example

### ISSUE THREAD

**Issue by nsryan2** [arfc/writing-checker#1]
Hey @osanstrong, this is a really cool tool that will help our workflow in the group! It seems as though this is still developing, but it's never too early to start documenting. You have some great inline comments, but you might want to consider a README for this repo to give people a sense of what the tool is and how to use it.

This issue can be closed with a PR that adds a `README.md` file to the top-level of this repository that includes a
1. project description,
2. code snippet,
3. summary of outputs, 
4. a link back to the checklist,
5. and what the contents of the repo are (a high level overview).

Once you've got a minimum working example, that would be great to include too!

**Comment by nsryan2** [comment]
@osanstrong it looks like this issue has been addressed by #4? If that's the case, we can close this issue!

**Comment by osanstrong** [comment]
Ah thanks! Looks like I forgot to resolve it when I merged the PR.
